os: osx

language: generic

cache:
  directories:
    - $HOME/.stack

addons:
  homebrew:
    packages:
      - haskell-stack
      - shunit2
      - icarus-verilog

install:
  make

script:
  make test
