name: Notice
on:
  push:
    paths:
      - stack.yaml
      - stack.yaml.lock
      - sv2v.cabal
      - notice.sh
      - NOTICE
jobs:
  notice:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: mstksg/setup-stack@v2
      - name: Regenerate NOTICE
        run: ./notice.sh > NOTICE
      - name: Validate NOTICE
        run: |
          if [ -n "`git status --porcelain`" ]; then
            echo "Notice differs!"
            PAGER= git diff
            exit 1
          fi
